version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ts-node-express 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Acekiz13112005
      POSTGRES_DB: ts_node_express_db

    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data